---
- name: Copy configuration files to target hosts with backup and config reload
  hosts: sonic_nodes
  become: true
  tasks:
    - name: Create a backup of the existing configuration file
      command: mv /etc/sonic/config_db.json /etc/sonic/config_db.json.bak
      args:
        creates: /etc/sonic/config_db.json.bak
      ignore_errors: yes
      register: backup_result

    - name: Copy new configuration files
      copy:
        src: "files/{{ inventory_hostname }}/config_db.json"
        dest: "/etc/sonic/config_db.json"
        mode: 0644

    - name: Reload configuration
      expect:
        command: sudo config reload
        responses:
          #'.*y/N.*': 'y'
          #'Clear current config and reload config in config_db format from the default config file(s) ? [y/N]:': 'y'
          (.*)y/N(.*): "y"
        timeout: 120
      ignore_errors: yes
      when: backup_result is not failed
      # async: 300  # Set the async timeout value to 180 seconds (adjust as needed)
      # poll: 15
      register: reload_result
 
    - debug: var=reload_result.stdout_lines
